[dev]
command = "vite"
port = 5173
targetPort = 3000
publish = "dist"
functions = "netlify-functions"

[build]
command = "npm run build"
publish = "dist"
functions = "netlify-functions"

[build.environment]
VITE_SUPABASE_URL = "sua_url_supabase"
VITE_SUPABASE_KEY = "sua_chave_supabase"
VITE_GEMINI_API_KEY = "sua_chave_gemini"
